import {StyleSheet} from 'react-native';
import {
  Colors,
  Metrics,
  moderateScale,
  verticalScale,
  horizontalScale,
  Fonts,
} from '../../theme';

export default StyleSheet.create({
  container: {},
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.transparent,
  },
  opacityView: {
    backgroundColor: Colors.black,
    opacity: 0.8,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  modalView: {
    width: Metrics.screenWidth * 0.85,
    backgroundColor: Colors.white,
    borderRadius: moderateScale(20),
    padding: moderateScale(10),
    shadowColor: Colors.shadow,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingHorizontal: moderateScale(30),
  },
  alertIconView: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    backgroundColor: Colors.unfilledRed,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: moderateScale(10),
  },
  alertIcon: {
    width: moderateScale(60),
    height: moderateScale(60),
    resizeMode: 'contain',
    left: moderateScale(-5),
  },
  headerText: {
    fontFamily: Fonts.type.PoppinsBold,
    fontSize: Fonts.size.h5,
    color: Colors.black,
    marginVertical: moderateScale(5),
  },
  descriptionText: {
    fontFamily: Fonts.type.PoppinsRegular,
    fontSize: Fonts.size.medium,
    color: Colors.placeHolderColor,
    marginVertical: moderateScale(10),
  },
  errorType: {
    textTransform: 'lowercase',
  },
  termsView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: moderateScale(20),
  },
  checkIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
    resizeMode: 'contain',
    marginRight: moderateScale(10),
  },
  termsText: {
    fontSize: moderateScale(16),
    color: Colors.grey,
  },
  buttonView: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: moderateScale(10),
  },
  cancelButton: {
    flex: 0.45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.grey,
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    height: moderateScale(44),
  },
  cancelText: {
    fontSize: moderateScale(14),
    fontWeight: 'bold',
    color: Colors.grey,
  },
  deleteButton: {
    flex: 0.45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.red,
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    height: moderateScale(44),
  },
  deleteText: {
    fontSize: moderateScale(14),
    fontWeight: 'bold',
    color: Colors.red,
  },
  seperator: {
    height: moderateScale(0.5),
    backgroundColor: Colors.seperatorColor,
    marginVertical: moderateScale(4),
  },
  buttonContainer: {
    height: verticalScale(50),
    width: horizontalScale(260),
    backgroundColor: Colors.appThemeColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: moderateScale(16),
    fontFamily: Fonts.type.PoppinsExtraLight,
  },
  oktext: {
    textTransform: 'uppercase',
  },
});
