import {StyleSheet} from 'react-native';
import {
  Colors,
  Metrics,
  moderateScale,
  verticalScale,
  horizontalScale,
  Fonts,
} from '../../theme';

export default StyleSheet.create({
  container: {},
  modalContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.transparentBlack,
  },
  modalView: {
    width: Metrics.screenWidth * 0.85,
    backgroundColor: Colors.white,
    borderRadius: moderateScale(20),
    padding: moderateScale(10),
    shadowColor: Colors.shadow,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    paddingHorizontal: moderateScale(30),
  },
  closeIconView: {
    height: moderateScale(30),
    alignItems: 'flex-end',
    marginVertical: moderateScale(10),
  },
  closeIcon: {
    width: moderateScale(25),
    height: moderateScale(25),
    resizeMode: 'contain',
    flexDirection: 'row-reverse',
  },
  alertIconView: {
    height: moderateScale(50),
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: moderateScale(10),
  },
  alertIcon: {
    width: moderateScale(60),
    height: moderateScale(60),
    resizeMode: 'contain',
  },
  descriptionText: {
    fontFamily: Fonts.type.PoppinsRegular,
    fontSize: moderateScale(12),
    color: Colors.black,
    marginVertical: verticalScale(10),
    paddingVertical: verticalScale(10),
    textAlign: 'center',
  },
  checkView: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkIcon: {
    width: moderateScale(60),
    height: moderateScale(60),
    resizeMode: 'contain',
    tintColor: Colors.white,
    backgroundColor: Colors.filledGreen,
    borderRadius: moderateScale(50),
    marginVertical: moderateScale(10),
  },
  buttonView: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: moderateScale(10),
  },
  cancelButton: {
    flex: 0.45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.grey,
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    height: moderateScale(44),
  },
  cancelText: {
    fontSize: moderateScale(14),
    fontWeight: 'bold',
    color: Colors.grey,
  },
  deleteButton: {
    flex: 0.45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.red,
    borderRadius: moderateScale(12),
    padding: moderateScale(10),
    height: moderateScale(44),
  },
  deleteText: {
    fontSize: moderateScale(14),
    fontWeight: 'bold',
    color: Colors.red,
  },
  seperator: {
    height: moderateScale(0.5),
    backgroundColor: Colors.seperatorColor,
    marginVertical: moderateScale(4),
  },
  buttonContainer: {
    height: verticalScale(50),
    width: horizontalScale(260),
    backgroundColor: Colors.appThemeColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: moderateScale(16),
    fontFamily: Fonts.type.PoppinsExtraLight,
  },
});
