import {translate} from '../i18n';
const strings = {
  myAccount: translate('myAccount'),
  preferences: translate('preferences'),
  userName: translate('userName'),
  password: translate('password'),
  emailPlaceholder: translate('emailPlaceholder'),
  passwordPlaceHolder: translate('passwordPlaceHolder'),
  confirmPasswordPlaceHolder: translate('confirmPasswordPlaceHolder'),
  userNamePlaceholder: translate('enterUserNamePlaceholder'),
  firstNamePlaceholder: translate('firstNamePlaceholder'),
  lastNamePlaceholder: translate('lastNamePlaceholder'),
  mobileNumberPlaceholder: translate('mobileNumberPlaceholder'),
  addressPlaceHolder: translate('addressPlaceHolder'),
  mailingAddressPlaceholder: translate('mailingAddressPlaceholder'),

  //Error Messages
  emptyEmail: translate('Email field can not be empty'),
  emptyPassword: translate('Password field can not be empty'),
  emptyMobile_no: translate('Mobile Number can not be empty'),
  emptyName: translate('Name can not be empty'),
  emptyFirstName: translate('First name can not be empty'),
  emptyLastName: translate('Last name can not be empty'),
  emptyAddress: translate('Address can not be empty'),
  emptyCountry: translate('emptyCountry'),
  emptyState: translate('emptyState'),
  emptyCity: translate('emptyCity'),
  emptyZipcode: translate('emptyZipcode'),
  emptyUserName: translate('User name field can not be empty'),
  errorValidFirstName: translate('errorValidFirstName'),
  errorValidLastName: translate('errorValidLastName'),
  invalidEmail: translate('Invalid Email Id'),
  invalidMobileNumber: translate('Invalid mobile number'),
  invalidPassword: translate('Password is Invalid.'),
  validName: translate('Must be greater than 2 letters'),
  minZipCode: translate('minZipCode'),
  maxZipCode: translate('maxZipCode'),
  inValidName: translate('Must be 75 characters or less'),
  valid: translate('Please enter valid string'),
  matchPassword: translate('Confirm Password must match with Password'),
  whiteSpaceNotAllowed: translate('whiteSpaceNotAllowed'),
  passwordShouldBe: translate('passwordShouldBe'),
  passwordNotMatch: translate('passwordNotMatch'),
  emptyConfirmPassword: translate('emptyConfirmPassword'),
  somethingWentWrong: translate('somethingWentWrong'),
  emptyPhoneNumber: translate('emptyPhoneNumber'),
  invalidZipCode: translate('invalidZipCode'),
  invalidFirstName: translate('invalidFirstName'),
  invalidLastName: translate('invalidLastName'),
  invalidUsername: translate('invalidUsername'),
  toLongFirstName: translate('toLongFirstName'),
  toLongLastName: translate('toLongLastName'),
  toLongUsername: translate('toLongUsername'),
  toLongEmail: translate('toLongEmail'),
  emptySubject: translate('emptySubject'),
  emptyMessage: translate('emptyMessage'),
  emptyPurchaseDate: translate('emptyPurchaseDate'),
  emptyLocationName: translate('emptyLocationName'),
  invalidProductName: translate('invalidProductName'),
  emptyReceiptName: translate('emptyReceiptName'),
  InvalidFilename: translate('InvalidFilename'),
  emptyReceiptImage: translate('emptyReceiptImage'),
  emptyWarrantyName: translate('emptyWarrantyName'),
  emptyStartDate: translate('emptyStartDate'),
  emptyEndDate: translate('emptyEndDate'),
  emptyCurrency: translate('emptyCurrency'),
  emptyPrice: translate('emptyPrice'),
  emptyProvider: translate('emptyProvider'),
  emptyWarrantyType: translate('emptyWarrantyType'),
  emptyServiceNumber: translate('emptyServiceNumber'),
  invalidInput: translate('invalidInput'),
  emptyLocationImage: translate('emptyLocationImage'),
  invalidYear: translate('invalidYear'),
  invalidPrice: translate('invalidPrice'),
  invalidServiceNumber: translate('invalidServiceNumber'),

  resend: translate('resend'),
  login: translate('login'),
  createAccount: translate('createAccount'),
  signup: translate('signup'),
  signIn: translate('signIn'),
  forgotPassword: translate('Forgot Password ?'),
  forgotUsername: translate('Forgot Username ?'),
  registerYourself: translate('Need an Account ?'),
  next: translate('Next'),
  hide: translate('hide'),
  show: translate('show'),
  forgotUsernameOrPassword: translate('forgotUsernameOrPassword'),
  alreadyHaveAccount: translate('alreadyHaveAccount'),
  signinUsingEmail: translate('signinUsingEmail'),
  termsPolicy: translate('termsPolicy'),
  iAgree: translate('I here by agree to all '),
  and: translate('and '),
  or: translate('or'),
  selectCountry: translate('selectCountry'),
  verificationLinkSent: translate('verificationLinkSent'),
  //reset username & password
  resetUsername: translate('resetUsername'),
  usrHeaderDesc: translate('usrHeaderDesc'),
  enterNewUsername: translate('enterNewUsername'),
  reEnterNewUsername: translate('reEnterNewUsername'),
  resetPassword: translate('resetPassword'),
  pwdHeaderDesc: translate('pwdHeaderDesc'),
  enterNewPassword: translate('enterNewPassword'),
  reEnterNewPassword: translate('reEnterNewPassword'),
  pleaseEnterNewUsername: translate('pleaseEnterNewUsername'),
  pleaseReEnterNewUsername: translate('pleaseReEnterNewUsername'),
  pleaseEnterNewPassword: translate('pleaseEnterNewPassword'),
  pleaseReEnterNewPassword: translate('pleaseReEnterNewPassword'),
  //forgot username or password
  recoverUsername: translate('recoverUsername'),
  recover: translate('recover'),
  forgotUsrDesc: translate('forgotUsrDesc'),
  forgotPwdDesc: translate('forgotPwdDesc'),
  didReceiveUsr: translate('didReceiveUsr'),
  forgotUsrPwdText: translate('forgotUsrPwdText'),
  forgotDesc: translate('forgotDesc'),
  verifyPhoneOrEmailDesc: translate('verifyPhoneOrEmailDesc'),
  pleaseEnterEmailOrPhone: translate('pleaseEnterEmailOrPhone'),
  enterEmailOrPhonePlaceholder: translate('enterEmailOrPhonePlaceholder'),
  verify: translate('verify'),
  sendOtp: translate('sendOtp'),
  terms: translate('terms'),
  privacyPolicy: translate('privacyPolicy'),
  termAndPolicyDeclaration: translate('termAndPolicyDeclaration'),
  authorizeMarketingTerm: translate('authorizeMarketingTerm'),
  authorizeShareTerm: translate('authorizeShareTerm'),
  submit: translate('submit'),
  reset: translate('reset'),
  timer: translate('14:59'),
  recoverEmail: translate('Please Enter Registered Email'),
  otp: translate('Please Enter OTP'),
  addressTerm: translate('addressTerm'),
  photoLibrary: translate('Photo Library'),
  takePhoto: translate('Take Photo'),
  cancel: translate('Cancel'),
  avatarImg: translate('Upload Image required'),
  unsupported: translate('Unsupported File Format'),
  products: translate('Products'),
  purchasedOn: translate('purchasedOn'),
  profile: translate('Profile'),
  setting: translate('Setting'),
  drawer: translate('Drawer'),

  //account setting stack
  theme: translate('Theme'),
  aqua: translate('Aqua'),
  yellow: translate('Yellow'),
  purple: translate('Purple'),
  alertAndNotifications: translate('alertAndNotifications'),
  warrantyExpiry: translate('warrantyExpiry'),
  locationUpdate: translate('Location Update'),
  productUpdate: translate('Product Update'),
  deviceAuthentication: translate('Device Authentication'),
  marketingAlert: translate('Marketing Alert'),
  authentication: translate('Authentication'),
  backupAndRestore: translate('Backup & Restore'),
  alerts: translate('alerts'),
  pushNotification: translate('Push Notification'),
  faceId: translate('faceId'),
  passCode: translate('passCode'),
  fingerPrint: translate('Finger Print'),
  backup: translate('Backup'),
  addLocation: translate('addLocation'),
  addNewLocation: translate('addNewLocation'),
  enterProductDetails: translate('enterProductDetails'),
  enterFeedDeatails: translate('enterFeedDeatails'),
  addProduct: translate('addProduct'),
  addPicture: translate('Add Picture'),
  productName: translate('productName'),
  selectCategory: translate('selectCategory'),
  selectType: translate('selectType'),
  manufacturer: translate('Manufacturer'),
  modelNoName: translate('Model No/Name'),
  price: translate('Price'),
  yearOfManufacture: translate('yearOfManufacture'),
  vendorName: translate('vendorName'),
  currency: translate('currency'),
  selectCurrency: translate('selectCurrency'),
  purchaseDate: translate('purchaseDate'),
  description: translate('Description'),
  miscNote: translate('miscNote'),
  receipt: translate('Receipt'),
  productNamePlaceholder: translate('productNamePlaceholder'),
  manufacturerPlaceholder: translate('manufacturerPlaceholder'),
  modelNoNamePlaceholder: translate('modelNoNamePlaceholder'),
  serialNoPlaceholder: translate('serialNoPlaceholder'),
  receiptPlaceholder: translate('receiptPlaceholder'),
  pricePlaceholder: translate('pricePlaceholder'),
  purchaseDatePlaceholder: translate('purchaseDatePlaceholder'),
  yearOfManufacturePlaceholder: translate('yearOfManufacturePlaceholder'),
  vendorNamePlaceholder: translate('vendorNamePlaceholder'),
  miscNotePlaceholder: translate('miscNotePlaceholder'),
  purchaseError: translate('purchaseError'),
  descriptionPlaceholder: translate('descriptionPlaceholder'),
  addReceipt: translate('addReceipt'),
  addTagNameForReceipt: translate('addTagNameForReceipt'),
  locationName: translate('Location Name'),
  address1: translate('address1'),
  address2: translate('address2'),
  city: translate('City'),
  zipCode: translate('Zip Code'),
  state: translate('State'),
  setAsDefault: translate('setAsDefault'),
  locationNamePlaceholder: translate('Enter Location Name'),
  cityPlaceholder: translate('cityPlaceholder'),
  zipCodePlaceholder: translate('Enter Zip Code'),
  statePlaceholder: translate('statePlaceholder'),
  newUsrHeaderText: translate('newUsrHeaderText'),
  emailOtp: translate('emailOtp'),
  phoneOtp: translate('phoneOtp'),
  emailOtpPlaceholder: translate('emailOtpPlaceholder'),
  phoneOtpPlaceholder: translate('phoneOtpPlaceholder'),
  emailOtpError: 'Please Enter Email OTP',
  phoneOtpError: translate('phoneOtpError'),
  OtpError: translate('OtpError'),
  InvalidOtpError: translate('InvalidOtpError'),
  resendOTP: translate('resendOTP'),
  home: translate('home'),
  // new user verification screen
  newUsrVerification: translate('newUsrVerification'),
  newUsrVerificationHeaderDesc: translate('newUsrVerificationHeaderDesc'),
  doNotReceive: translate('doNotReceive'),
  resendViaEmail: translate('resendViaEmail'),
  resendViaSms: translate('resendViaSms'),
  resendViaEmailDesc: translate('resendViaEmailDesc'),
  resendViaSmsDesc: translate('resendViaSmsDesc'),
  // recover user or password
  verifyEmail: translate('verifyEmail'),
  recoverUsrPwdHeaderDesc: translate('recoverUsrPwdHeaderDesc'),
  toRevocerYourUsername: translate('toRevocerYourUsername'),
  toRevocerYourPassword: translate('toRevocerYourPassword'),
  verifyEmailToProceed: translate('verifyEmailToProceed'),
  verifyPhoneToProceed: translate('verifyPhoneToProceed'),
  // edit profile Screen
  editProfile: translate('editProfile'),
  save: translate('save'),
  firstNameLastName: translate('firstNameLastName'),
  mobile: translate('mobile'),
  emailAddress: translate('emailAddress'),
  // profile screen
  personalInfo: translate('personalInfo'),
  name: translate('name'),
  email: translate('email'),
  phone: translate('phone'),
  security: translate('security'),
  change: translate('change'),
  profileCheckboxText1: translate('profileCheckboxText1'),
  profileCheckboxText2: translate('profileCheckboxText2'),

  // More screen
  more: translate('more'),
  accountSettings: translate('accountSettings'),
  receiptsList: translate('receiptsList'),
  warrantyList: translate('warrantyList'),
  helpAndSupport: translate('helpAndSupport'),
  contact: translate('contact'),
  about: translate('about'),
  logout: translate('logout'),
  feed: translate('Feed'),
  // change password screen
  changePassword: translate('changePassword'),
  changePwdHeaderDesc: translate('changePwdHeaderDesc'),
  currentPassword: translate('currentPassword'),
  newPassword: translate('newPassword'),
  confirmNewPassword: translate('confirmNewPassword'),
  update: translate('update'),

  //ReceiptsList Screen
  search: translate('search'),
  // edit Account
  editAccount: translate('editAccount'),
  edit: translate('edit'),
  add: translate('add'),
  // alert notification
  deviceActivation: translate('deviceActivation'),
  emailNotification: translate('emailNotification'),
  notifications: translate('notifications'),
  savedAddresses: translate('savedAddresses'),
  remove: translate('remove'),
  addNewAddress: translate('addNewAddress'),

  // Contact Us
  contactUs: translate('contactUs'),
  typeYourMessageHere: translate('typeYourMessageHere'),
  subject: translate('subject'),
  // Theme
  darkMode: translate('darkMode'),
  lightMode: translate('lightMode'),
  system: translate('system'),
  systemDesc: translate('systemDesc'),

  // Warranty Details
  warrantyDuration: translate('warrantyDuration'),
  warrantyValid: translate('warrantyValid'),
  viewWarrantyCard: translate('viewWarrantyCard'),
  warrantyOfParts: translate('warrantyOfParts'),
  locations: translate('locations'),
  // notification screen
  today: translate('today'),
  thisWeek: translate('thisWeek'),
  markAllAsRead: translate('markAllAsRead'),

  //Filter Screen
  filter: translate('filter'),
  byLocation: translate('byLocation'),
  byCategory: translate('byCategory'),
  byDate: translate('byDate'),
  from: translate('from'),
  to: translate('to'),
  applyFilter: translate('applyFilter'),

  //Add Location
  enterLocationDetails: translate('enterLocationDetails'),
  country: translate('country'),
  typeOfProperty: translate('typeOfProperty'),
  countryPlaceholder: translate('countryPlaceholder'),
  addPhoto: translate('addPhoto'),
  typeOfPropertyError: translate('typeOfPropertyError'),

  //Delete Location
  deleteLocation: translate('deleteLocation'),
  delete: translate('Delete'),
  deleteAll: translate('deleteAll'),
  deleteNotifications: translate('deleteNotifications'),
  sureToDeleteNotifications: translate('sureToDeleteNotifications'),
  deleteProduct: translate('deleteProduct'),
  sureToDeleteProduct: translate('sureToDeleteProduct'),

  selectAll: translate('selectAll'),
  unSelectAll: translate('unSelectAll'),
  done: translate('done'),

  // invalid popup
  invalidPhoneEmail: translate('invalidPhoneEmail'),
  ok: translate('ok'),
  // verified
  verified: translate('verified'),
  gotoHome: translate('gotoHome'),
  moveProductToNewLocation: translate('moveProductToNewLocation'),
  selectLocation: translate('selectLocation'),
  move: translate('move'),

  productLocation: translate('productLocation'),

  //QR code screen
  scanAnyQrCode: translate('scanAnyQrCode'),
  scanQrBarCode: translate('scanQrBarCode'),
  skipAndEnterDetailManually: translate('skipAndEnterDetailManually'),
  barcodeNotScanned: translate('barcodeNotScanned'),
  skipToEnterDetaManually: translate('skipToEnterDetaManually'),
  qrErrorDesc: translate('qrErrorDesc'),
  enterManually: translate('enterManually'),
  skip: translate('skip'),

  //Product Detail
  serialNo: translate('serialNo'),
  purchasedDate: translate('purchasedDate'),
  modelNo: translate('modelNo'),
  manufacture: translate('manufacture'),
  quantity: translate('quantity'),
  minLevel: translate('minLevel'),
  total: translate('total'),
  textNotification: translate('textNotification'),
  privacy: translate('privacy'),

  sortBy: translate('sortBy'),
  continue: translate('continue'),
  saveChanges: translate('saveChanges'),
  privacyNotice: translate('privacyNotice'),

  redirectToLogin: translate('redirectToLogin'),
  resetLinkSentTo: translate('resetLinkSentTo'),
  clickHere: translate('clickHere'),
  toResend: translate('toResend'),
  biometricAuthentication: translate('biometricAuthentication'),
  confirmtOTP: translate('confirmtOTP'),
  loginFailed: translate('loginFailed'),
  yes: translate('yes'),
  no: translate('no'),
  confirmLogout: translate('confirmLogout'),
  logoutConfirmationMessage: translate('logoutConfirmationMessage'),
  byWarrantyExpiryDate: translate('byWarrantyExpiryDate'),
  category: translate('category'),
  type: translate('type'),
  byPurchaseDate: translate('byPurchaseDate'),
  fullName: translate('fullName'),
  pendingVerification: translate('pendingVerification'),
  clickToVerify: translate('clickToVerify'),
  savedAddress: translate('savedAddress'),
  physicalAddress: translate('physicalAddress'),
  mailingAddress: translate('mailingAddress'),
  sameAsPhysicalAddress: translate('sameAsPhysicalAddress'),
  firstName: translate('firstName'),
  lastName: translate('lastName'),
  address1PlaceHolder: translate('address1PlaceHolder'),
  address2PlaceHolder: translate('address2PlaceHolder'),
  noLocation: translate('noLocation'),
  addLocationItem: translate('addLocationItem'),
  editLocation: translate('editLocation'),
  lastUpdated: translate('lastUpdated'),
  recentlyAdded: translate('recentlyAdded'),
  purchased: translate('purchased'),
  mostRecentFirst: translate('mostRecentFirst'),
  oldestFirst: translate('oldestFirst'),
  youCant: translate('youCant'),
  sureToDeleteThese: translate('sureToDeleteThese'),
  sureToDeleteThis: translate('sureToDeleteThis'),
  editProduct: translate('editProduct'),
  noProduct: translate('noProduct'),
  addProductItem: translate('addProductItem'),
  applySort: translate('applySort'),
  enterAddressDetails: translate('enterAddressDetails'),
  warrantyName: translate('warrantyName'),
  warrantyPartName: translate('warrantyPartName'),
  warrantyStart: translate('warrantyStart'),
  warrantyEnd: translate('warrantyEnd'),
  warrantyType: translate('warrantyType'),
  warrantyProvider: translate('warrantyProvider'),
  warrantyServiceNumber: translate('warrantyServiceNumber'),
  addWarranty: translate('addWarranty'),
  addWarrantySlip: translate('addWarrantySlip'),
  uploadPartWarrantySlip: translate('uploadPartWarrantySlip'),
  addItem: translate('addItem'),
  productHasPartWarranty: translate('productHasPartWarranty'),
  productWarranty: translate('productWarranty'),
  warrantyPart: translate('warrantyPart'),
  willExpiredOn: translate('willExpiredOn'),
  productDetails: translate('productDetails'),
  warrantyStarts: translate('warrantyStarts'),
  warrantyEnds: translate('warrantyEnds'),
  left: translate('left'),
  expired: translate('expired'),
  viewReceipt: translate('viewReceipt'),
  viewWarranty: translate('viewWarranty'),
  warrantyDetail: translate('warrantyDetail'),
  editWarranty: translate('editWarranty'),
  productsAssociated: translate('productsAssociated'),
  noReceiptFound: translate('noReceiptFound'),
  status: translate('status'),
  editReceipt: translate('editReceipt'),
  saved: translate('saved'),
  warrantyCoverage: translate('warrantyCoverage'),
  assetsValue: translate('assetsValue'),
  categories: translate('categories'),
  noNotificationsFound: translate('noNotificationsFound'),
  confirmChangePreference: translate('confirmChangePreference'),
  preferenceConfirmationMessage: translate('preferenceConfirmationMessage'),
  noWarrantyCard: translate('noWarrantyCard'),
  noAssertData: translate('noAssertData'),
  noCategoryData: translate('noCategoryData'),
  noLocationData: translate('noLocationData'),
  close: translate('close'),
  noDataFound: translate('noDataFound'),
  deleted: translate('deleted'),
  deleteAccount: translate('deleteAccount'),
  areYouSure: translate('areYouSure'),
  deleteLocationDescription: translate('deleteLocationDescription'),
  noAddress: translate('noAddress'),
  cameraPermission: translate('cameraPermission'),
  appNeedCameraPermission: translate('appNeedCameraPermission'),
  externalStoragePermission: translate('externalStoragePermission'),
  appNeedStoragePermission: translate('appNeedStoragePermission'),
  optional: translate('optional'),
  required: translate('required'),
  unsupportedFileSize: translate('unsupportedFileSize'),
  facebookLogin: translate('facebookLogin'),
  googleLogin: translate('googleLogin'),
  appleLogin: translate('appleLogin'),
  noInternet: translate('noInternet'),
  doYouDiscard: translate('doYouDiscard'),
  discard: translate('discard'),
  cookiePolicy: translate('cookiePolicy'),
  eula: translate('eula'),
  signInTermAndPolicyDeclaration: translate('signInTermAndPolicyDeclaration'),
  productScanError: translate('productScanError'),
  deleteWarranty: translate('deleteWarranty'),
  sureToDeleteWarranty: translate('sureToDeleteWarranty'),
  policies: translate('policies'),
  termsAndConditions: translate('termsAndConditions'),
  eulaPolicy: translate('eulaPolicy'),
  searchHere: translate('searchHere'),
  noLocationError: translate('noLocationError'),
  selectState: translate('selectState'),
  selectCity: translate('selectCity'),
  appUpdate: translate('appUpdate'),
  timeToUpdate: translate('timeToUpdate'),
  appUpdateDescription: translate('appUpdateDescription'),
  notNow: translate('notNow'),
  toLongSubject: translate('toLongSubject'),
  toLongDescription: translate('toLongDescription'),
  toLongNotes: translate('toLongNotes'),
  minimumTwoDigit: translate('minimumTwoDigit'),
  otherCity: translate('otherCity'),
  enterCityName: translate('enterCityName'),
  buyaAkkoWarranty:translate('buyaAkkoWarranty'),
  //FEEED//

  author:translate('author'),
  title:translate('title'),
  upload:translate('upload'),

};

export default strings;
