import {Platform, StyleSheet} from 'react-native';
import {
  Colors,
  Fonts,
  horizontalScale,
  Metrics,
  moderateScale,
  verticalScale,
} from '../../../theme';

export default StyleSheet.create({
  headerContainer: {
    paddingHorizontal: horizontalScale(10),
  },
  locationHeader: {
    fontFamily: Fonts.type.PoppinsMedium,
    fontSize: Fonts.size.medium,
    color: Colors.placeHolderColor,
    textTransform: 'uppercase',
    marginHorizontal: moderateScale(25),
    marginTop: moderateScale(5),
  },
  locationView: {
    flexDirection: 'row',
    marginTop: moderateScale(5),
    marginHorizontal: moderateScale(25),
    shadowColor: Colors.black,
    shadowRadius: 4,
    shadowOffset: {height: 4, width: 0},
    shadowOpacity: 0.2,
    elevation: 2,
    backgroundColor: Colors.themeBackground,
    padding: verticalScale(12),
    borderRadius: verticalScale(10),
    borderWidth: 0.5,
    borderColor: Colors.white,
  },
  leftView: {},
  leftImage: {
    width: horizontalScale(80),
    height: verticalScale(80),
    resizeMode: 'contain',
    borderRadius: moderateScale(10),
  },
  locationDetail: {
    width: '65%',
    marginLeft: horizontalScale(15),
  },
  locationName: {
    fontFamily: Fonts.type.PoppinsSemiBold,
    fontSize: Fonts.size.medium,
    color: Colors.black,
  },
  addressView: {
    flexDirection: 'row',
    marginVertical: verticalScale(5),
  },
  locationIcn: {
    width: horizontalScale(12),
    height: verticalScale(12),
    resizeMode: 'contain',
    marginRight: horizontalScale(5),
    marginTop: verticalScale(5),
  },
  locationAddress: {
    fontFamily: Fonts.type.PoppinsRegular,
    fontSize: Fonts.size.small,
    color: Colors.placeHolderColor,
  },
  phoneView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  phoneIcn: {
    width: moderateScale(12),
    height: moderateScale(12),
    resizeMode: 'contain',
    marginRight: moderateScale(5),
  },
  locationPhone: {
    fontFamily: Fonts.type.PoppinsRegular,
    fontSize: Fonts.size.small,
    color: Colors.placeHolderColor,
  },
  listContainer: {
    flex: 1,
    marginTop: moderateScale(20),
    marginHorizontal: moderateScale(10),
  },
  listTitle: {
    fontFamily: Fonts.type.PoppinsMedium,
    fontSize: Fonts.size.medium,
    color: Colors.placeHolderColor,
    textTransform: 'uppercase',
    marginBottom: verticalScale(5),
    marginHorizontal: moderateScale(15),
  },
  buttonView: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: horizontalScale(20),
  },
  rightIconButtonText: {
    fontSize: moderateScale(12),
    fontWeight: 'bold',
    color: Colors.blue,
  },
  seperator: {
    height: moderateScale(0.5),
    backgroundColor: Colors.seperatorColor,
  },
  selectOperationView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: moderateScale(60),
    backgroundColor: Colors.white,
    paddingHorizontal: moderateScale(20),
    borderWidth: 1,
    borderColor: Colors.transparent,
    borderTopColor: Colors.seperatorColor,
  },
  searchContainer: {
    marginVertical: moderateScale(-3),
    borderWidth: 1,
    backgroundColor: Colors.inputBackground,
    height: moderateScale(40),
    width: Metrics.screenWidth - horizontalScale(120),
    borderRadius: moderateScale(10),
  },
  inputText: {
    fontWeight: 'normal',
    marginLeft: moderateScale(5),
    fontFamily: Fonts.type.PoppinsRegular,
  },
  leftIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
    marginRight: moderateScale(15),
  },
  mainView: {
    marginTop: Platform.OS === 'ios' ? verticalScale(20) : verticalScale(30),
    justifyContent: 'center',
    height: verticalScale(80),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(5),
    height: moderateScale(60),
    marginTop: Platform.OS === 'ios' ? verticalScale(0) : verticalScale(30),
  },
  centerView: {
    alignContent: 'center',
    justifyContent: 'center',
  },
  mainHeader: {
    fontSize: Fonts.size.h4,
    fontFamily: Fonts.type.PoppinsBold,
    color: Colors.black,
  },
  title: {
    fontSize: moderateScale(25),
    fontFamily: Fonts.type.PoppinsBold,
    color: Colors.black,
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    textTransform: 'capitalize',
  },
  subtitleText: {
    fontSize: Fonts.size.small,
    color: Colors.black,
    textAlign: 'center',
    marginVertical: moderateScale(10),
  },
  backButtonContainer: {
    flex: 0.1,
    paddingVertical: moderateScale(10),
    paddingRight: moderateScale(5),
  },
  backButtonStyle: {
    height: verticalScale(20),
    width: horizontalScale(20),
    paddingRight: moderateScale(40),
    resizeMode: 'contain',
  },
  rightButtonView: {
    flex: 0.1,
  },
  rightButtonStyle: {alignSelf: 'center'},
  rightButtonTextStyle: {color: '#105ad0', fontWeight: '600'},
  rightButtonContainer: {
    flex: 0.1,
    right: 20,
    height: verticalScale(80),
    justifyContent: 'center',
  },
  headerImageStyle: {
    height: verticalScale(80),
    width: horizontalScale(80),
    backgroundColor: Colors.appThemeColor,
    borderRadius: 40,
    alignSelf: 'center',
  },
  actionContainer: {
    flex: 0.2,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  iconView: {
    marginLeft: moderateScale(10),
  },
  iconStyle: {
    width: moderateScale(20),
    height: moderateScale(20),
    resizeMode: 'contain',
    marginRight: horizontalScale(20),
  },
  buttonText: {
    fontSize: Fonts.size.medium,
    fontFamily: Fonts.type.PoppinsSemiBold,
    color: Colors.blueText,
  },
  centerFlex: {
    flex: 0.65,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: Metrics.screenHeight * 0.12,
  },
  emptyData: {
    fontFamily: Fonts.type.PoppinsRegular,
    fontSize: Fonts.size.regular,
    color: Colors.black,
  },
  bannerView: {
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  closeIcon: {
    height: moderateScale(10),
    width: moderateScale(10),
    tintColor: Colors.white,
  },
  closeButton: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    right: 0,
    top: 0,
    height: moderateScale(20),
    width: moderateScale(20),
    backgroundColor: Colors.lightGrey,
    borderRadius: moderateScale(1),
  },
  plusIconView: {
    position: 'absolute',
    bottom: verticalScale(70),
    right: horizontalScale(15),
    backgroundColor: Colors.yellow,
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.grey,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 1,
    shadowRadius: 4.65,

    elevation: 8,
  },
});
